### ISSUE TITLE
Zeek Splunk

### ISSUE THREAD

**Issue by arun81** [ewingc/zeek-splunk#1]
Hi ,

Thanks for the project ..

Can you please confirm whether Corelight App for Splunk is required to View Zeek Logs or there is other such mechanism to view Zeek Logs

Is there any step by step document to get this working .

Thanks & Regards

**Comment by ewingc** [comment]
Hi @arun81. While the Corelight App for Splunk is not required to view Zeek logs, it definitely has nice dashboards and other features that highlight the Zeek logs. I would like to get the Corelight App for Splunk working with this project in the future. I know the Corelight App for Splunk works very well with the Corelight sensors and streaming logs. In the meantime, you can search using Splunk queries. For example, the following query will show you the top source IP: `* | table id.orig_h | stats count by id.orig_h | sort by count desc`.

The README.md file is intended to document the prerequisites and usage of this project. What step-by-step instructions are you looking for, or what do you feel is missing from the README.md?

Thanks!

**Comment by arun81** [comment]
Hi .
Can you please help us in Step by Step configuration in Splunk app like indexing , searching and viewing of logs
Hope this helps for your understanding 

Thanks.

**Comment by arun81** [comment]
Can you please help in creating the video as it will be easy to install for beginners 

Thanks

**Comment by ewingc** [comment]
Thanks for the request. However, step-by-step instructions on usage of Splunk is out of the scope of this project and there is already an enormous amount of documentation already from https://docs.splunk.com/Documentation that I wouldn't want to duplicate. If you follow the instructions in the README.md of this project, your Zeek logs should be indexed and searchable.
